QT       -= core
QT       -= gui

TEMPLATE = lib

# DEFINES += STR_UTIL_ENABLE_CUSTOM_UNICODE_OPERATIONS
DEFINES += TEALSCRIPT_NO_EIGEN

QMAKE_CXXFLAGS += -std=c++20 -fPIC -Wno-unused-function
QMAKE_CXXFLAGS_RELEASE -= -O2
QMAKE_CXXFLAGS_RELEASE += -O3
QMAKE_CFLAGS_RELEASE -= -O2
QMAKE_CFLAGS_RELEASE += -O3

SOURCES += \
    libmain.cpp
